#!/bin/bash

menu="\033[41;1;37m"
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"
fim="\033[0m"
RCLOCAL=/etc/rc.local

echo -e "$azulClaro
Digite a string a ser bloqueada
$fim"

read -p "String: " ip

iptables -I FORWARD -m string --algo bm --string "$ip" -j DROP
iptables -I OUTPUT -m string --algo bm --string "$ip" -j DROP
iptables -I INPUT -m string --algo bm --string "$ip" -j DROP
sed -i "1 a\iptables -I FORWARD -m string --algo bm --string "$ip" -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -m string --algo bm --string "$ip" -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -m string --algo bm --string "$ip" -j DROP $ip -j DROP" $RCLOCAL
