#!/bin/bash
RCLOCAL=/etc/rc.local
iptables -A FORWARD -i eth0 -s 203.205.151.106 -j DROP
iptables -A INPUT -i eth0 -s 203.205.151.106 -j DROP
iptables -I FORWARD -s 203.205.151.106 -j DROP
iptables -I OUTPUT -s 203.205.151.106 -j DROP
iptables -I INPUT -s 203.205.151.106 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.142.208 -j DROP
iptables -A INPUT -i eth0 -s 203.205.142.208 -j DROP
iptables -I FORWARD -s 203.205.142.208 -j DROP
iptables -I OUTPUT -s 203.205.142.208 -j DROP
iptables -I INPUT -s 203.205.142.208 -j DROP
iptables -A FORWARD -i eth0 -s 115.159.100.85 -j DROP
iptables -A INPUT -i eth0 -s 115.159.100.85 -j DROP
iptables -I FORWARD -s 115.159.100.85 -j DROP
iptables -I OUTPUT -s 115.159.100.85 -j DROP
iptables -I INPUT -s 115.159.100.85 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.138.240 -j DROP
iptables -A INPUT -i eth0 -s 203.205.138.240 -j DROP
iptables -I FORWARD -s 203.205.138.240 -j DROP
iptables -I OUTPUT -s 203.205.138.240 -j DROP
iptables -I INPUT -s 203.205.138.240 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.138.244 -j DROP
iptables -A INPUT -i eth0 -s 203.205.138.244 -j DROP
iptables -I FORWARD -s 203.205.138.244 -j DROP
iptables -I OUTPUT -s 203.205.138.244 -j DROP
iptables -I INPUT -s 203.205.138.244 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.48 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.48 -j DROP
iptables -I FORWARD -s 203.205.158.48 -j DROP
iptables -I OUTPUT -s 203.205.158.48 -j DROP
iptables -I INPUT -s 203.205.158.48 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.151.14 -j DROP
iptables -A INPUT -i eth0 -s 203.205.151.14 -j DROP
iptables -I FORWARD -s 203.205.151.14 -j DROP
iptables -I OUTPUT -s 203.205.151.14 -j DROP
iptables -I INPUT -s 203.205.151.14 -j DROP
iptables -A FORWARD -i eth0 -s 119.28.164.222 -j DROP
iptables -A INPUT -i eth0 -s 119.28.164.222 -j DROP
iptables -I FORWARD -s 119.28.164.222 -j DROP
iptables -I OUTPUT -s 119.28.164.222 -j DROP
iptables -I INPUT -s 119.28.164.222 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.60 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.60 -j DROP
iptables -I FORWARD -s 203.205.158.60 -j DROP
iptables -I OUTPUT -s 203.205.158.60 -j DROP
iptables -I INPUT -s 203.205.158.60 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.138.243 -j DROP
iptables -A INPUT -i eth0 -s 203.205.138.243 -j DROP
iptables -I FORWARD -s 203.205.138.243 -j DROP
iptables -I OUTPUT -s 203.205.138.243 -j DROP
iptables -I INPUT -s 203.205.138.243 -j DROP
iptables -A FORWARD -i eth0 -s 182.254.116.117 -j DROP
iptables -A INPUT -i eth0 -s 182.254.116.117 -j DROP
iptables -I FORWARD -s 182.254.116.117 -j DROP
iptables -I OUTPUT -s 182.254.116.117 -j DROP
iptables -I INPUT -s 182.254.116.117 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.146.0/24 -j DROP
iptables -A INPUT -i eth0 -s 203.205.146.0/24 -j DROP
iptables -I FORWARD -s 203.205.146.0/24 -j DROP
iptables -I OUTPUT -s 203.205.146.0/24 -j DROP
iptables -I INPUT -s 203.205.146.0/24 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.0.0/16 -j DROP
iptables -A INPUT -i eth0 -s 203.205.0.0/16 -j DROP
iptables -I FORWARD -s 203.205.0.0/16 -j DROP
iptables -I OUTPUT -s 203.205.0.0/16 -j DROP
iptables -I INPUT -s 203.205.0.0/16 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.0/24 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.0/24 -j DROP
iptables -I FORWARD -s 203.205.158.0/24 -j DROP
iptables -I OUTPUT -s 203.205.158.0/24 -j DROP
iptables -I INPUT -s 203.205.158.0/24 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.40 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.40 -j DROP
iptables -I FORWARD -s 203.205.158.40 -j DROP
iptables -I OUTPUT -s 203.205.158.40 -j DROP
iptables -I INPUT -s 203.205.158.40 -j DROP
iptables -A FORWARD -i eth0 -s 140.207.54.57 -j DROP
iptables -A INPUT -i eth0 -s 140.207.54.57 -j DROP
iptables -I FORWARD -s 140.207.54.57 -j DROP
iptables -I OUTPUT -s 140.207.54.57 -j DROP
iptables -I INPUT -s 140.207.54.57 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.43 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.43 -j DROP
iptables -I FORWARD -s 203.205.158.43 -j DROP
iptables -I OUTPUT -s 203.205.158.43 -j DROP
iptables -I INPUT -s 203.205.158.43 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.41 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.41 -j DROP
iptables -I FORWARD -s 203.205.158.41 -j DROP
iptables -I OUTPUT -s 203.205.158.41 -j DROP
iptables -I INPUT -s 203.205.158.41 -j DROP
iptables -A FORWARD -i eth0 -s 119.28.164.219 -j DROP
iptables -A INPUT -i eth0 -s 119.28.164.219 -j DROP
iptables -I FORWARD -s 119.28.164.219 -j DROP
iptables -I OUTPUT -s 119.28.164.219 -j DROP
iptables -I INPUT -s 119.28.164.219 -j DROP
iptables -A FORWARD -i eth0 -s 119.28.164.223 -j DROP
iptables -A INPUT -i eth0 -s 119.28.164.223 -j DROP
iptables -I FORWARD -s 119.28.164.223 -j DROP
iptables -I OUTPUT -s 119.28.164.223 -j DROP
iptables -I INPUT -s 119.28.164.223 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.61 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.61 -j DROP
iptables -I FORWARD -s 203.205.158.61 -j DROP
iptables -I OUTPUT -s 203.205.158.61 -j DROP
iptables -I INPUT -s 203.205.158.61 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.211.75 -j DROP
iptables -A INPUT -i eth0 -s 203.205.211.75 -j DROP
iptables -I FORWARD -s 203.205.211.75 -j DROP
iptables -I OUTPUT -s 203.205.211.75 -j DROP
iptables -I INPUT -s 203.205.211.75 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.219.228 -j DROP
iptables -A INPUT -i eth0 -s 203.205.219.228 -j DROP
iptables -I FORWARD -s 203.205.219.228 -j DROP
iptables -I OUTPUT -s 203.205.219.228 -j DROP
iptables -I INPUT -s 203.205.219.228 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.158.62 -j DROP
iptables -A INPUT -i eth0 -s 203.205.158.62 -j DROP
iptables -I FORWARD -s 203.205.158.62 -j DROP
iptables -I OUTPUT -s 203.205.158.62 -j DROP
iptables -I INPUT -s 203.205.158.62 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.179.145 -j DROP
iptables -A INPUT -i eth0 -s 203.205.179.145 -j DROP
iptables -I FORWARD -s 203.205.179.145 -j DROP
iptables -I OUTPUT -s 203.205.179.145 -j DROP
iptables -I INPUT -s 203.205.179.145 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.142.207 -j DROP
iptables -A INPUT -i eth0 -s 203.205.142.207 -j DROP
iptables -I FORWARD -s 203.205.142.207 -j DROP
iptables -I OUTPUT -s 203.205.142.207 -j DROP
iptables -I INPUT -s 203.205.142.207 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.151.193 -j DROP
iptables -A INPUT -i eth0 -s 203.205.151.193 -j DROP
iptables -I FORWARD -s 203.205.151.193 -j DROP
iptables -I OUTPUT -s 203.205.151.193 -j DROP
iptables -I INPUT -s 203.205.151.193 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.128.130 -j DROP
iptables -A INPUT -i eth0 -s 203.205.128.130 -j DROP
iptables -I FORWARD -s 203.205.128.130 -j DROP
iptables -I OUTPUT -s 203.205.128.130 -j DROP
iptables -I INPUT -s 203.205.128.130 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.138.241 -j DROP
iptables -A INPUT -i eth0 -s 203.205.138.241 -j DROP
iptables -I FORWARD -s 203.205.138.241 -j DROP
iptables -I OUTPUT -s 203.205.138.241 -j DROP
iptables -I INPUT -s 203.205.138.241 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.146.45 -j DROP
iptables -A INPUT -i eth0 -s 203.205.146.45 -j DROP
iptables -I FORWARD -s 203.205.146.45 -j DROP
iptables -I OUTPUT -s 203.205.146.45 -j DROP
iptables -I INPUT -s 203.205.146.45 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.146.122 -j DROP
iptables -A INPUT -i eth0 -s 203.205.146.122 -j DROP
iptables -I FORWARD -s 203.205.146.122 -j DROP
iptables -I OUTPUT -s 203.205.146.122 -j DROP
iptables -I INPUT -s 203.205.146.122 -j DROP
iptables -A FORWARD -i eth0 -s 203.205.128.159 -j DROP
iptables -A INPUT -i eth0 -s 203.205.128.159 -j DROP
iptables -I FORWARD -s 203.205.128.159 -j DROP
iptables -I OUTPUT -s 203.205.128.159 -j DROP
iptables -I INPUT -s 203.205.128.159 -j DROP
sed -i "1 a\iptables -I INPUT -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.128.159 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.128.159 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.128.159 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.128.159 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.128.159 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.146.122 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.146.45 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.138.241 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.128.130 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.151.193 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.142.207$ip -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.142.207 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.179.145 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.62 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.219.228 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.211.75 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.61 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 119.28.164.223 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 119.28.164.219 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.41 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.41 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.41 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.41 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.41 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.40 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 140.207.54.57 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.43 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.43 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.43 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.43 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.43 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.146.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.146.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.146.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.146.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.146.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I INPUT -s 203.205.158.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I OUTPUT -s 203.205.158.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -I FORWARD -s 203.205.158.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A INPUT -i eth0 -s 203.205.158.0/24 -j DROP" $RCLOCAL
sed -i "1 a\iptables -A FORWARD -i eth0 -s 203.205.158.0/24 -j DROP" $RCLOCAL
route add -n 115.159.100.85 gw 127.0.0.1 lo
route add -n 119.28.164.219 gw 127.0.0.1 lo
route add -n 119.28.164.220 gw 127.0.0.1 lo
route add -n 119.28.164.222 gw 127.0.0.1 lo
route add -n 119.28.164.223 gw 127.0.0.1 lo
route add -n 140.207.54.57 gw 127.0.0.1 lo
route add -n 182.254.116.117 gw 127.0.0.1 lo
route add -n 203.205.142.207 gw 127.0.0.1 lo
route add -n 203.205.179.145 gw 127.0.0.1 lo
route add -n 203.205.219.228 gw 127.0.0.1 lo
route add -n 203.205.211.75 gw 127.0.0.1 lo
route add -n 203.205.158.61 gw 127.0.0.1 lo
route add -n 119.28.164.223 gw 127.0.0.1 lo
route add -n 119.28.164.219 gw 127.0.0.1 lo
route add -n 203.205.128.130 gw 127.0.0.1 lo
route add -n 203.205.128.159 gw 127.0.0.1 lo
route add -n 203.205.138.240 gw 127.0.0.1 lo
route add -n 203.205.138.241 gw 127.0.0.1 lo
route add -n 203.205.138.243 gw 127.0.0.1 lo
route add -n 203.205.138.244 gw 127.0.0.1 lo
route add -n 203.205.142.207 gw 127.0.0.1 lo
route add -n 203.205.142.208 gw 127.0.0.1 lo
route add -n 203.205.146.45 gw 127.0.0.1 lo
route add -n 203.205.146.122 gw 127.0.0.1 lo
route add -n 203.205.151.14 gw 127.0.0.1 lo
route add -n 203.205.151.106 gw 127.0.0.1 lo
route add -n 203.205.151.193 gw 127.0.0.1 lo
route add -n 203.205.158.40 gw 127.0.0.1 lo
route add -n 203.205.158.41 gw 127.0.0.1 lo
route add -n 203.205.158.43 gw 127.0.0.1 lo
route add -n 203.205.158.48 gw 127.0.0.1 lo
route add -n 203.205.158.60 gw 127.0.0.1 lo
route add -n 203.205.158.61 gw 127.0.0.1 lo
route add -n 203.205.158.62 gw 127.0.0.1 lo
route add -n 203.205.179.145 gw 127.0.0.1 lo
route add -n 203.205.211.75 gw 127.0.0.1 lo
route add -n 203.205.219.228 gw 127.0.0.1 lo
