#!/bin/bash

iptables -A FORWARD -i eth0 -s 140.210.64.5 -j REJECT
iptables -A INPUT -i eth0 -s 140.210.64.5 -j REJECT
iptables -I FORWARD -s 140.210.64.5 -j REJECT
iptables -I OUTPUT -s 140.210.64.5 -j REJECT
iptables -I INPUT -s 140.210.64.5 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.63 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.63 -j REJECT
iptables -I FORWARD -s 203.205.158.63 -j REJECT
iptables -I OUTPUT -s 203.205.158.63 -j REJECT
iptables -I INPUT -s 203.205.158.63 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.183.16 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.183.16 -j REJECT
iptables -I FORWARD -s 119.28.183.16 -j REJECT
iptables -I OUTPUT -s 119.28.183.16 -j REJECT
iptables -I INPUT -s 119.28.183.16 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.138.0/24 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.138.0/24 -j REJECT
iptables -I FORWARD -s 203.205.138.0/24 -j REJECT
iptables -I OUTPUT -s 203.205.138.0/24 -j REJECT
iptables -I INPUT -s 203.205.138.0/24 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.146.0/24 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.146.0/24 -j REJECT
iptables -I FORWARD -s 203.205.146.0/24 -j REJECT
iptables -I OUTPUT -s 203.205.146.0/24 -j REJECT
iptables -I INPUT -s 203.205.146.0/24 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.0/24 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.0/24 -j REJECT
iptables -I FORWARD -s 203.205.158.0/24 -j REJECT
iptables -I OUTPUT -s 203.205.158.0/24 -j REJECT
iptables -I INPUT -s 203.205.158.0/24 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.219.228 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.219.228 -j REJECT
iptables -I FORWARD -s 203.205.219.228 -j REJECT
iptables -I OUTPUT -s 203.205.219.228 -j REJECT
iptables -I INPUT -s 203.205.219.228 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.211.75 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.211.75 -j REJECT
iptables -I FORWARD -s 203.205.211.75 -j REJECT
iptables -I OUTPUT -s 203.205.211.75 -j REJECT
iptables -I INPUT -s 203.205.211.75 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.179.145 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.179.145 -j REJECT
iptables -I FORWARD -s 203.205.179.145 -j REJECT
iptables -I OUTPUT -s 203.205.179.145 -j REJECT
iptables -I INPUT -s 203.205.179.145 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.62 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.62 -j REJECT
iptables -I FORWARD -s 203.205.158.62 -j REJECT
iptables -I OUTPUT -s 203.205.158.62 -j REJECT
iptables -I INPUT -s 203.205.158.62 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.61 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.61 -j REJECT
iptables -I FORWARD -s 203.205.158.61 -j REJECT
iptables -I OUTPUT -s 203.205.158.61 -j REJECT
iptables -I INPUT -s 203.205.158.61 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.60 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.60 -j REJECT
iptables -I FORWARD -s 203.205.158.60 -j REJECT
iptables -I OUTPUT -s 203.205.158.60 -j REJECT
iptables -I INPUT -s 203.205.158.60 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.48 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.48 -j REJECT
iptables -I FORWARD -s 203.205.158.48 -j REJECT
iptables -I OUTPUT -s 203.205.158.48 -j REJECT
iptables -I INPUT -s 203.205.158.48 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.43 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.43 -j REJECT
iptables -I FORWARD -s 203.205.158.43 -j REJECT
iptables -I OUTPUT -s 203.205.158.43 -j REJECT
iptables -I INPUT -s 203.205.158.43 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.41 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.41 -j REJECT
iptables -I FORWARD -s 203.205.158.41 -j REJECT
iptables -I OUTPUT -s 203.205.158.41 -j REJECT
iptables -I INPUT -s 203.205.158.41 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.40 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.40 -j REJECT
iptables -I FORWARD -s 203.205.158.40 -j REJECT
iptables -I OUTPUT -s 203.205.158.40 -j REJECT
iptables -I INPUT -s 203.205.158.40 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.151.193 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.151.193 -j REJECT
iptables -I FORWARD -s 203.205.151.193 -j REJECT
iptables -I OUTPUT -s 203.205.151.193 -j REJECT
iptables -I INPUT -s 203.205.151.193 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.151.106 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.151.106 -j REJECT
iptables -I FORWARD -s 203.205.151.106 -j REJECT
iptables -I OUTPUT -s 203.205.151.106 -j REJECT
iptables -I INPUT -s 203.205.151.106 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.151.14 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.151.14 -j REJECT
iptables -I FORWARD -s 203.205.151.14 -j REJECT
iptables -I OUTPUT -s 203.205.151.14 -j REJECT
iptables -I INPUT -s 203.205.151.14 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.146.122 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.146.122 -j REJECT
iptables -I FORWARD -s 203.205.146.122 -j REJECT
iptables -I OUTPUT -s 203.205.146.122 -j REJECT
iptables -I INPUT -s 203.205.146.122 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.146.45 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.146.45 -j REJECT
iptables -I FORWARD -s 203.205.146.45 -j REJECT
iptables -I OUTPUT -s 203.205.146.45 -j REJECT
iptables -I INPUT -s 203.205.146.45 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.142.208 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.142.208 -j REJECT
iptables -I FORWARD -s 203.205.142.208 -j REJECT
iptables -I OUTPUT -s 203.205.142.208 -j REJECT
iptables -I INPUT -s 203.205.142.208 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.142.207 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.142.207 -j REJECT
iptables -I FORWARD -s 203.205.142.207 -j REJECT
iptables -I OUTPUT -s 203.205.142.207 -j REJECT
iptables -I INPUT -s 203.205.142.207 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.138.244 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.138.244 -j REJECT
iptables -I FORWARD -s 203.205.138.244 -j REJECT
iptables -I OUTPUT -s 203.205.138.244 -j REJECT
iptables -I INPUT -s 203.205.138.244 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.138.243 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.138.243 -j REJECT
iptables -I FORWARD -s 203.205.138.243 -j REJECT
iptables -I OUTPUT -s 203.205.138.243 -j REJECT
iptables -I INPUT -s 203.205.138.243 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.138.241 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.138.241 -j REJECT
iptables -I FORWARD -s 203.205.138.241 -j REJECT
iptables -I OUTPUT -s 203.205.138.241 -j REJECT
iptables -I INPUT -s 203.205.138.241 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.138.240 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.138.240 -j REJECT
iptables -I FORWARD -s 203.205.138.240 -j REJECT
iptables -I OUTPUT -s 203.205.138.240 -j REJECT
iptables -I INPUT -s 203.205.138.240 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.128.159 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.128.159 -j REJECT
iptables -I FORWARD -s 203.205.128.159 -j REJECT
iptables -I OUTPUT -s 203.205.128.159 -j REJECT
iptables -I INPUT -s 203.205.128.159 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.128.130 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.128.130 -j REJECT
iptables -I FORWARD -s 203.205.128.130 -j REJECT
iptables -I OUTPUT -s 203.205.128.130 -j REJECT
iptables -I INPUT -s 203.205.128.130 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.219 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.219 -j REJECT
iptables -I FORWARD -s 119.28.164.219 -j REJECT
iptables -I OUTPUT -s 119.28.164.219 -j REJECT
iptables -I INPUT -s 119.28.164.219 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.223 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.223 -j REJECT
iptables -I FORWARD -s 119.28.164.223 -j REJECT
iptables -I OUTPUT -s 119.28.164.223 -j REJECT
iptables -I INPUT -s 119.28.164.223 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.158.61 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.158.61 -j REJECT
iptables -I FORWARD -s 203.205.158.61 -j REJECT
iptables -I OUTPUT -s 203.205.158.61 -j REJECT
iptables -I INPUT -s 203.205.158.61 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.211.75 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.211.75 -j REJECT
iptables -I FORWARD -s 203.205.211.75 -j REJECT
iptables -I OUTPUT -s 203.205.211.75 -j REJECT
iptables -I INPUT -s 203.205.211.75 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.219.228 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.219.228 -j REJECT
iptables -I FORWARD -s 203.205.219.228 -j REJECT
iptables -I OUTPUT -s 203.205.219.228 -j REJECT
iptables -I INPUT -s 203.205.219.228 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.179.145 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.179.145 -j REJECT
iptables -I FORWARD -s 203.205.179.145 -j REJECT
iptables -I OUTPUT -s 203.205.179.145 -j REJECT
iptables -I INPUT -s 203.205.179.145 -j REJECT
iptables -A FORWARD -i eth0 -s 203.205.142.207 -j REJECT
iptables -A INPUT -i eth0 -s 203.205.142.207 -j REJECT
iptables -I FORWARD -s 203.205.142.207 -j REJECT
iptables -I OUTPUT -s 203.205.142.207 -j REJECT
iptables -I INPUT -s 203.205.142.207 -j REJECT
iptables -A FORWARD -i eth0 -s 182.254.116.117 -j REJECT
iptables -A INPUT -i eth0 -s 182.254.116.117 -j REJECT
iptables -I FORWARD -s 182.254.116.117 -j REJECT
iptables -I OUTPUT -s 182.254.116.117 -j REJECT
iptables -I INPUT -s 182.254.116.117 -j REJECT
iptables -A FORWARD -i eth0 -s 140.207.54.57 -j REJECT
iptables -A INPUT -i eth0 -s 140.207.54.57 -j REJECT
iptables -I FORWARD -s 140.207.54.57 -j REJECT
iptables -I OUTPUT -s 140.207.54.57 -j REJECT
iptables -I INPUT -s 140.207.54.57 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.223 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.223 -j REJECT
iptables -I FORWARD -s 119.28.164.223 -j REJECT
iptables -I OUTPUT -s 119.28.164.223 -j REJECT
iptables -I INPUT -s 119.28.164.223 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.222 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.222 -j REJECT
iptables -I FORWARD -s 119.28.164.222 -j REJECT
iptables -I OUTPUT -s 119.28.164.222 -j REJECT
iptables -I INPUT -s 119.28.164.222 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.220 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.220 -j REJECT
iptables -I FORWARD -s 119.28.164.220 -j REJECT
iptables -I OUTPUT -s 119.28.164.220 -j REJECT
iptables -I INPUT -s 119.28.164.220 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.220 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.220 -j REJECT
iptables -I FORWARD -s 119.28.164.220 -j REJECT
iptables -I OUTPUT -s 119.28.164.220 -j REJECT
iptables -I INPUT -s 119.28.164.220 -j REJECT
iptables -A FORWARD -i eth0 -s 119.28.164.219 -j REJECT
iptables -A INPUT -i eth0 -s 119.28.164.219 -j REJECT
iptables -I FORWARD -s 119.28.164.219 -j REJECT
iptables -I OUTPUT -s 119.28.164.219 -j REJECT
iptables -I INPUT -s 119.28.164.219 -j REJECT
iptables -A FORWARD -i eth0 -s 115.159.100.85 -j REJECT
iptables -A INPUT -i eth0 -s 115.159.100.85 -j REJECT
iptables -I FORWARD -s 115.159.100.85 -j REJECT
iptables -I OUTPUT -s 115.159.100.85 -j REJECT
iptables -I INPUT -s 115.159.100.85 -j REJECT
