#!/bin/bash

IP=$(wget -qO- ipv4.icanhazip.com)
read -p "Para continuar confirme o IP deste servidor: " -e -i $IP

iptables -F
iptables -X
iptables -t nat -F
iptables -t nat -X
iptables -t mangle -F
iptables -t mangle -X

echo Configurando...
sleep 1
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

iptables -A INPUT -p udp -j ACCEPT
iptables -A OUTPUT -p udp -j ACCEPT
iptables -A OUTPUT -p udp -j ACCEPT

#iptables -A FORWARD -p tcp --dport 7300 -j ACCEPT
#iptables -A INPUT -p tcp --dport 7300 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 7300 -j ACCEPT
#iptables -A FORWARD -p udp --dport 7300 -j ACCEPT
#iptables -A INPUT -p udp --dport 7300 -j ACCEPT
#iptables -A OUTPUT -p udp --dport 7300 -j ACCEPT

#iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
#iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
#iptables -t filter -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT

#iptables -A OUTPUT -p tcp -d $IP --dport 443 -m state --state NEW -j ACCEPT
#iptables -A OUTPUT -p tcp -d $IP --dport 80 -m state --state NEW -j ACCEPT
#iptables -A OUTPUT -p udp -d $IP --dport 443 -m state --state NEW -j ACCEPT
#iptables -A OUTPUT -p udp -d $IP --dport 80 -m state --state NEW -j ACCEPT
#iptables -A OUTPUT -p udp -d $IP --dport 7300 -m state --state NEW -j ACCEPT
#iptables -A OUTPUT -p tcp -d $IP --dport 7300 -m state --state NEW -j ACCEPT

#iptables -A INPUT -p udp -d $IP --dport 7300 -m state --state NEW -j ACCEPT
#iptables -A INPUT -p tcp -d $IP --dport 7300 -m state --state NEW -j ACCEPT

iptables -A OUTPUT -p tcp --dport 53 -m state --state NEW -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -m state --state NEW -j ACCEPT

iptables -A INPUT -p tcp --dport 22 -j ACCEPT
#iptables -A INPUT -p tcp --dport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 22 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
#iptables -A INPUT -p tcp --dport 8080 -j ACCEPT
#iptables -A INPUT -p tcp --dport 80 -j ACCEPT
#iptables -A INPUT -p tcp --dport 3128 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 8080 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 80 -j ACCEPT
#iptables -A FORWARD -p tcp --dport 8080 -j ACCEPT
#iptables -A FORWARD -p tcp --dport 80 -j ACCEPT
#iptables -A INPUT -p tcp --dport 3000 -j ACCEPT
#iptables -A OUTPUT -p tcp --dport 3000 -j ACCEPT
#iptables -A INPUT -p icmp --icmp-type echo-request -j DROP

#iptables -A FORWARD -m string --algo bm --string "BitTorrent" -j DROP
#iptables -A FORWARD -m string --algo bm --string "BitTorrent protocol" -j DROP
#iptables -A FORWARD -m string --algo bm --string "peer_id=" -j DROP
#iptables -A FORWARD -m string --algo bm --string ".torrent" -j DROP
#iptables -A FORWARD -m string --algo bm --string "announce.php?passkey=" -j DROP
#iptables -A FORWARD -m string --algo bm --string "torrent" -j DROP
#iptables -A FORWARD -m string --algo bm --string "announce" -j DROP
#iptables -A FORWARD -m string --algo bm --string "info_hash" -j DROP 
#iptables -A FORWARD -m string --string "get_peers" --algo bm -j DROP
#iptables -A FORWARD -m string --string "announce_peer" --algo bm -j DROP
#iptables -A FORWARD -m string --string "find:_node" --algo bm -j DROP


echo -e "\033[1;36mFirewall moficicado
Portas 443 2510 8080 8014 80
Bloqueio ICMP
Bloqueio Torrent
Pequena proteçao DDoS

CASO QUEIRA TIRAR ESSAS REGRAS IPTABLES EXECUTE A FERRAMENTA ResetFirewall\033[0m"
