#!/bin/sh

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Atualizando" ; tput sgr0
echo ""

echo "Digite o dominio"
read -p ": " D1

IP=$(wget -qO- ipv4.icanhazip.com)
IP1=$(host $D1 | awk '{print $NF}')

apt-get update
apt-get upgrade -y

clear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Removendo restos de instalação antiga" ; tput sgr0
echo ""

sleep 1.5s

rm -rf /root/.git
rm -rf /root/VPS
rm -rf /root/install
rm -rf /root/vyvrn
rm -rf /home/ubuntu/.git
rm -rf /home/ubuntu/VPS
rm -rf /home/ubuntu/install

clear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando GIT" ; tput sgr0
echo ""

sleep 1.5s

apt-get install git -y
git clone https://github.com/jluanb/VPS.git
clear
cd VPS
rm -rf README.md
rm -rf install
for arqs in `ls`
do
rm /bin/$arqs 2>/dev/null
mv $arqs /bin
chmod +x /bin/$arqs
done

clear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando Dropbear" ; tput sgr0

sleep 2s

#apt-get install dropbear -y

#echo "NO_START=0
#DROPBEAR_PORT=80
#DROPBEAR_RECEIVE_WINDOW=65536" > /etc/default/dropbear

#service dropbear restart

echo "Port 2510
Port 22
Protocol 2
#Compression yes
KeyRegenerationInterval 3600
ServerKeyBits 1024
SyslogFacility AUTH
LogLevel INFO
LoginGraceTime 60
PermitRootLogin yes
StrictModes yes
RSAAuthentication yes
PubkeyAuthentication yes
IgnoreRhosts yes
RhostsRSAAuthentication no
HostbasedAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no
PasswordAuthentication yes
X11Forwarding yes
X11DisplayOffset 10
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
Banner /etc/banner.txt
#UseLogin no
AcceptEnv LANG LC_*
Subsystem sftp /usr/lib/openssh/sftp-server
UsePAM yes
UseDns no" > /etc/ssh/sshd_config

echo "Digite a msg do Banner"
read -p ": " banner
echo "$banner" > /etc/banner.txt

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Otimizando Sysctl" ; tput sgr0
echo ""

sleep 2s

echo "#kernel.printk = 3 4 1 3
#net.ipv4.conf.all.log_martians = 1
#net.ipv4.conf.all.secure_redirects = 1
#net.ipv4.conf.all.send_redirects = 0
#net.ipv4.conf.all.accept_redirects = 0
#net.ipv6.conf.all.accept_redirects = 0
#net.ipv4.conf.all.accept_source_route = 0
#net.ipv6.conf.all.accept_source_route = 0
#net.ipv6.conf.all.forwarding=1
#net.ipv4.conf.default.rp_filter=1
#net.ipv4.conf.all.rp_filter=1
net.ipv4.ip_forward=1
fs.file-max=51200
net.core.rmem_max=67108864
net.core.wmem_max=67108864
net.core.netdev_max_backlog=250000
net.core.somaxconn=4096
net.ipv4.tcp_syncookies=1
net.ipv4.tcp_tw_reuse=1
net.ipv4.tcp_tw_recycle=1
net.ipv4.tcp_fin_timeout=30
net.ipv4.tcp_keepalive_time=1200
net.ipv4.ip_local_port_range=10000 65000
net.ipv4.tcp_max_syn_backlog=8192
net.ipv4.tcp_max_tw_buckets=5000
net.ipv4.tcp_fastopen=3
net.ipv4.tcp_mem=25600 51200 102400
net.core.rmem_max=67108864
net.core.wmem_max=67108864
net.ipv4.tcp_rmem=4096 87380 67108864
net.ipv4.tcp_wmem=4096 65536 67108864
net.core.netdev_max_backlog=250000
net.ipv4.tcp_mtu_probing=1
net.ipv4.tcp_congestion_control=westwood" > /etc/sysctl.conf
sysctl -p
echo "westwood" > /proc/sys/net/ipv4/tcp_congestion_control


tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Instalando Vnstat, Pktstat, Ntop, Nethogs e dependencias" ; tput sgr0
echo ""

sleep 1.5s

	apt-get install vnstat -y
	apt-get install pktstat -y
	apt-get install ntop graphviz -y
	apt-get install make g++ -y
	apt-get install libncurses5-dev -y
	apt-get install libpcap-dev -y
	apt-get install mitmproxy -y
	apt-get install nmap -y
	apt-get install hping3 -y
	apt-get install nload -y

	# Baixe o código fonte, compile e instale:
	wget http://github.com/raboof/nethogs/archive/v0.8.5.tar.gz
	tar xf v0.8.5.tar.gz
	cd ./nethogs-0.8.5/
	make && make install
	rm -rf /root/VPS
	rm -fr /home/ubuntu/VPS
	rm -rf /root/install
	rm -rf /root/vyvrn
        rm -rf /home/ubuntu/install
	mkdir /etc/VpsPackdir
	mkdir /etc/Vpspackdir/limite
	exit
fi

vpsmanager
