#!/bin/sh

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Atualizando Kernel" ; tput sgr0
echo ""

sleep 2s

apt-get update
apt-get install linux-virtual -y

export GRUB_CONFIG=`sudo find /boot -name "grub.cfg"`

update-grub

grub-set-default 'Ubuntu, with Linux 4.4.0-24-generic'

update-grub

clear

tput setaf 7 ; tput setab 4 ; tput bold ; printf '%32s%s%-13s\n' "Reiniciando..." ; tput sgr0
echo ""

sleep 2s

reboot
