#!/bin/bash

apt-get build-essential apache2 apache2-utils git -y

echo "# If you just change the port or add more ports here, you will likely also
# have to change the VirtualHost statement in
# /etc/apache2/sites-enabled/000-default.conf

Listen 8080

<IfModule ssl_module>
	Listen 443
</IfModule>

<IfModule mod_gnutls.c>
	Listen 443
</IfModule>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet" > /etc/apache2/ports.conf

cd /var/www/html/
git clone https://github.com/darold/squidanalyzer.git
mv squidanalyzer squidanalyzer-sources
cd squidanalyzer-sources

perl Makefile.PL \
     LOGFILE=/var/log/squid3/access.log \
     BINDIR=/usr/bin \
     CONFDIR=/etc/squidanalyzer \
     HTMLDIR=/var/www/html/squidanalyzer \
     BASEURL=/ \
     MANDIR=/usr/man/man3 \
     DOCDIR=/usr/share/doc/squidanalyzer
     
make && make install
cp -Rfa /var/www/html/squidanalyzer-sources/resources/images/* /var/www/html/squidanalyzer/images/
echo "####
# This file is the default configuration file for SquidAnalyzer
# Edit it to match your needs and copy it under /etc/squidanalyzer/squidanalyzer.conf
#####

# Path where SquidAnalyzer should dump all HTML and images files.
# Choose a path that can be read by a Web browser
Output	/var/www/html/squidanalyzer

# The URL of the SquidAnalyzer javascript, HTML and images files.
WebUrl	/

# Set the path to the Squid, squidGuard and/or ufdbGuard log files
LogFile	/var/log/squid3/access.log

# If you want to use DNS name instead of client Ip address as username enable
# this directive. When you don't have authentication, the username is set to
# the client ip address, this allow you to use the DNS name instead.
# Note that you must have a working DNS resolution and that it can really slow
# down the generation of reports.
UseClientDNSName	0

# If you have enabled UseClientDNSName and have lot of ip addresses that do
# not resolve you may want to increase the DNS lookup timeout. By default
# SquidAnalyzer will stop to lookup a DNS name after 0.0001 second (100 ms).
DNSLookupTimeout	0.0001

# Set the file containing network alias name. Network are
# show as Ip addresses so if you want to display name instead
# create a file with this format :
# LOCATION_NAME	IP_NETWORK_ADDRESS
# Separator must be a tabulation
NetworkAlias	/etc/squidanalyzer/network-aliases

# Set the file containing user alias name. If you don't have auth_proxy
# enable user are seen as Ip addresses, or if you want to replace login
# name by full user name, create a file with this format :
# FULL_USERNAME	IP_ADDRESS || LOGIN_NAME
# Separator must be a tabulation
UserAlias	/etc/squidanalyzer/user-aliases

# How do we sort Network, User and user's Url report screen
# Value can be: bytes, hits or duration. Default is bytes.
OrderNetwork	bytes
OrderUser	bytes
OrderUrl	bytes

# How do we sort Mime types report screen
# Value can be: bytes or hits. Default is bytes.
OrderMime	bytes

# Should we display user URL details. This will show all URL read
# by user. Take care to have enougth space disk for large user.
UrlReport	1

# Enable this directive if you don't want the tree Top URL and Domain HTML tables.
# You will just have the table of Url/Domain ordered per hits then you can still
# sort the URL/Domain order by clicking on each column
UrlHitsOnly	0

# Should we display user details. This will show statistics per user.
UserReport	1

# Run in quiet mode or print debug information
QuietMode	1

# Cost of the bandwidth per Mb. If you want to generate invoice per Mb
# for bandwidth traffic this can help you. Value 0 mean no cost.
CostPrice	0

# Currency of the bandwidth cost
Currency	&euro;

# Top number of url to show from all url extracted from the log
TopNumber	100

# Top number of url to preserve on each data file sorted by OrderUrl.
# On huge access log it will improve a lot the performances but you
# will have less precision in the top url. Default to 0, all url will
# be stored.
TopStorage	0

# Path to the file containing client ip addresses, network ip address,
# and/or auth login to exclude from report
Exclude	/etc/squidanalyzer/excluded

# Path to the file containing client ip addresses, network ip address,
# and/or auth login to include into the report. Other entries will be
# excluded by default.
Include	/etc/squidanalyzer/included

# Translation Lang	/etc/squidanalyzer/lang/en_US.txt,
# en_US.txt, ru_RU.txt, uk_UA.txt, cs_CZ.txt, pl_PL.txt and de_DE.txt).
# Default to:
#Lang	/etc/squidanalyzer/lang/pt_BR.txt

# Date format used to display date (year = %y, month = %m and day = %d)
# You can also use %M to replace month by its 3 letters abbreviation.
DateFormat	%d-%m-%y

# Set this to 1 if you want to anonymize all user login. The username
# will be replaced by an unique id that change at each squid-analyzer
# run. Default disable.
AnonymizeLogin	0

# Adds peer cache hit (CD_SIBLING_HIT) to be taken has local cache hit.
# Enabled by default, you must disabled it if you don't want to report
# peer cache hit onto your stats.
SiblingHit	1

# Set the default unit for transfert size. Default is BYTES, other possible
# values are KB, MB and GB
TransfertUnit	MB

# Minimum percentage of data in pie's graphs to not be placed in the others item.
MinPie		2

# Set this to your locale to display generated date in your language. Default
# is to use strftime. If you want date in German for example, set it to de_DE.
# For french, fr_FR should do the work.
#Locale		pt_BR

# By default SquidAnalyzer is saving current collected statistics each time
# a new hour is found in log file. Most of the time this is enough but if
# you have huge log file and don't have enough memory this will slow down the
# parser by forcing Perl to use temporaries files. Use lower value following
# your memory and the size of your log file, on very huge log file with lot of
# requests/seconde a value of 30 minutes (1800) or less should help.
WriteDelay	3600

# Use this directive to show the top N users that look at an URL or a domain.
# Set it to 0 to disable this feature.
TopUrlUser	10

# This directive allow you to replace the SquidAnalyze logo by your custom
# logo. The default value is defined as follow:
# <a href="$self->{WebUrl}">
# <img src="$self->{WebUrl}images/logo-squidanalyzer.png" title="SquidAnalyzer $VERSION" border="0">
# </a> SquidAnalyzer
# Feel free to define your own header but take care to not break current design.
#CustomHeader	<a href="http://my.isp.dom/"><img src="http://my.isp.dom/logo.png" title="My ISP link" border="0" width="100" height="110"></a> My ISP Company

# This directive allow exclusion of some unwanted methods in report statistics
# like HEAD, POST, CONNECT, etc. Can be a comma separated list of methods.
#ExcludedMethods	HEAD

# This directive allow exclusion of some unwanted mimetypes in report statistics
# like text/html, text/plain, or more generally text/*, etc. Can be a comma separated
# list of perl regular expression.
#ExcludedMimes	text/.*,image/.*

# This directive allow exclusion of some unwanted codes in report statistics
# like TCP_DENIED/403 which are generated when a user accesses a page the first
# time without authentication. Can be a comma separated list of methods.
#ExcludedCodes	TCP_DENIED/403

# When SquidAnalyzer find a corrupted line in his data file, it exit immedialtly.
# You can force him to wait for a certain amount of errors before exiting. Of
# course you might want to remove the corrupted line before the next run. This
# can be useful if you have special characters in some fields like mime type.
#MaxFormatError	0

# Set timezone to use when SquidAnalyzer is used in a different server than
# the one running squid and there is a different timezone between these two
# machine. The value must follow format: +/-HH. Default is to use local time.
TimeZone	-03

# Enable this directive if you want to include port number into Url statistics.
# Default is to remove the port information from the Url.
#UseUrlPort	0

# Enable this directive if you want to apply immedialtly the changes made in
# aliases files to avoid duplicates. You still have to use --rebuild to
# recreate previous reports with new aliases. Enabling this will imply a lost
# of performances with huges log files.
#UpdateAlias	0

# The two following configuration directive allow you to specify a start and
# stop time. Log line out of this time range will not be parsed.
#TimeStart	00:00
#TimeStop	23:59" > /etc/squidanalyzer/squidanalyzer.conf

echo "<VirtualHost *:80>
  ServerName squidanalyzer.douglasqsantos.com.br
  ServerAdmin webmaster@douglasqsantos.com.br
  DocumentRoot "/var/www/squidanalyzer"
   <Directory "/var/www/squidanalyzer">
     Options +FollowSymLinks +FollowSymLinks +MultiViews
     AllowOverride All
     AuthUserFile /etc/apache2/access/squidanalyzer-htpasswd
     AuthName "SquidAnalyzer"
     AuthType Basic
     require valid-user
   </Directory>
  ServerSignature Off
  LogLevel info
  ErrorLog /var/log/apache2/squidanalyzer-error.log
  CustomLog /var/log/apache2/squidanalyzer-access.log combined
</VirtualHost>" > /etc/apache2/sites-available/squidanalyzer.conf

mkdir /etc/apache2/access/
htpasswd -s -c /etc/apache2/access/squidanalyzer-htpasswd squidanalyzer
a2dissite 000-default
a2ensite squidanalyzer.conf

echo "0 */10     *       *       *    /usr/bin/squid-analyzer > /dev/null 2>&1" >> /tmp/crontab.LE4ENn/crontab

/usr/bin/squid-analyzer > /dev/null 2>&1
mv /var/www/html/squidanalyzer /var/www/html
/etc/init.d/apache2 restart

