#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi
clear
echo -e "     \033[40;1;37m  VpsManager by Luan  \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m 
[1] Alterarlimite \033[1;30m(limite de conexoes simultaneas )\033[1;33m 
[2] Criarusuario \033[1;30m(Criar usuarios )\033[1;33m 
[3] Mudardata \033[1;30m(Mudar data de Expiração )\033[1;33m 
[4] Alterarsenha \033[1;30m(Alterar senha do usuario )\033[1;33m 
[5] Expcleaner \033[1;30m(Limpar logins vencidos )\033[1;33m 
[6] Remover \033[1;30m(Remover usuarios )\033[1;33m 
[7] Sshlimiter \033[1;30m(Número de logins simultaneos)\033[1;33m 
[8] Sshmonitor \033[1;30m(Monitorar ususarios )\033[1;33m 
[9] Backup \033[1;30m(Cria e restaura backups )\033[1;33m 
[10] Firewall \033[1;30m(Proteger VPS contra ataques )\033[1;33m 
[11] Resetfirewall \033[1;30m(Resetar regras iptables )\033[1;33m 
[12] Speedtest \033[1;30m(Teste velocidade VPS )\033[1;33m 
[13] Systemdetalhes \033[1;30m(Detalhes do sistemas )\033[1;33m 
[14] Vpn \033[1;30m(Instala Openvpn no servidor )\033"
read -p ": " opcao

case $opcao in
 1)
  alterarlimite;;
 2)
  criarusuario;;
 3)
  mudardata;;
 4)
  alterarsenha;;
 5)
  expcleaner;;
 6)
  remover;;
 7)
  sshlimiter;;
 8)
  sshmonitor;;
 9)
  backup;;
 10)
  firewall;;
 11)
  resetfirewall;;
 12)
  speedtest;;
 13)
  systemdetalhes;;
 14)
  vpn;;
 *)
  id > /dev/null 2> /dev/null
esac
