#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi
clear
echo -e "     \033[40;1;37m  VpsManager by Luan  \033[0m"
echo -e "\033[1;37mEscolha uma das opções:    \033[1;37mPara Sair Ctrl + C\033[1;33m 
[1] Attrepo \033[1;0m(Atualizar repositorio do Vpsmanager )\033[1;33m
[2] Attssh \033[1;0m(Atualizar configurações Ssh )\033[1;33m
[3] Alterarlimite \033[1;0m(limite de conexoes simultaneas )\033[1;33m 
[4] Criarusuario \033[1;0m(Criar usuarios )\033[1;33m 
[5] Mudardata \033[1;0m(Mudar data de Expiração )\033[1;33m 
[6] Alterarsenha \033[1;0m(Alterar senha do usuario )\033[1;33m 
[7] Expcleaner \033[1;0m(Limpar logins vencidos )\033[1;33m 
[8] Remover \033[1;0m(Remover usuarios )\033[1;33m 
[9] Sshlimiter \033[1;0m(Número de logins simultaneos)\033[1;33m 
[10] Sshmonitor \033[1;0m(Monitorar ususarios )\033[1;33m 
[11] Backup \033[1;0m(Cria e restaura backups )\033[1;33m 
[12] Firewall \033[1;0m(Proteger VPS contra ataques )\033[1;33m 
[13] Resetfirewall \033[1;0m(Resetar regras iptables )\033[1;33m 
[14] Speedtest \033[1;0m(Teste velocidade VPS )\033[1;33m 
[15] Systemdetalhes \033[1;0m(Detalhes do sistemas )\033[1;33m 
[16] Vpn \033[1;0m(Instala Openvpn no servidor )\033[1;33m
[17] Installbadudp \033[1;0m(Instalar Badudp )\033[1;33m
[18] Ipp2p \033[1;0m(Bloquear Torrent[compativel com kernel 3.13 only )\033[1;33m
[19] Kernel3.13 \033[1;0m(Downgrade kernel )\033[1;33m
[20] Kernelup \033[1;0m(Atualizar kernel para útima versão disponivel )\033[1;33m
[21] Urldump \033[1;0m(Captura urls HTTP e HTTPS )\033[1;33m
[22] Flooder \033[1;0m(Ferramentas Flood DoS)\033[1;33m
[23] Installvnc \033[1;0m(Instalar ambiente grafico no servidor)\033[;0m"
read -p ": " opcao

case $opcao in
 1)
  attrepo;;
 2)
  attssh;;
 3)
  alterarlimite;;
 4)
  criarusuario;;
 5)
  mudardata;;
 6)
  alterarsenha;;
 7)
  expcleaner;;
 8)
  remover;;
 9)
  sshlimiter;;
 10)
  sshmonitor;;
 11)
  backup;;
 12)
  firewall;;
 13)
  resetfirewall;;
 14)
  speedtest;;
 15)
  systemdetalhes;;
 16)
  vpn;;
 17)
  badvpn;;
 18)
  ipp2p;;
 19)
  kernel3.13;;
 20)
  kernelup;;
 21)
  urldump;;
 22)
  flooder;;
 23)
  installvnc;;
 *)
  id > /dev/null 2> /dev/null
esac
